export const mskCases = [
  {
    caseNumber: 1,
    title: "Scaphoid Waist Fracture",
    section: "Fractures & trauma",
    modality: "Plain Film",
    clinicalHistory: "22-year-old male presents with radial-sided wrist pain following a fall onto an outstretched hand (FOOSH) 10 days ago. Initial radiographs at the time of injury were reported as normal.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [2, 4, 5],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 2,
    title: "Weber B Ankle Fracture-Dislocation",
    section: "Fractures & trauma",
    modality: "Plain Film",
    clinicalHistory: "45-year-old female presents with ankle pain and swelling after twisting her ankle stepping off a kerb. Unable to weight-bear.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [2, 4, 5],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 3,
    title: "Anterior Shoulder Dislocation with Hill-Sachs and Bankart Lesions",
    section: "Joint instability & internal derangement",
    modality: "MRI",
    clinicalHistory: "28-year-old male rugby player with recurrent anterior shoulder dislocations. Third episode in 18 months. MRI requested for surgical planning.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 4,
    title: "Burst Fracture of L1",
    section: "Fractures & trauma",
    modality: "CT",
    clinicalHistory: "35-year-old male fell from a height of approximately 3 metres. Complains of severe midline thoracolumbar pain. No neurological deficit on examination.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [2, 4, 5],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 5,
    title: "Osteosarcoma of the Distal Femur",
    section: "Aggressive bone lesion",
    modality: "Plain Film",
    clinicalHistory: "14-year-old male presents with a 6-week history of persistent right knee pain, worse at night. Localised swelling noted over the distal thigh. No history of trauma.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 6,
    title: "Ewing Sarcoma of the Femoral Diaphysis",
    section: "Aggressive bone lesion",
    modality: "MRI",
    clinicalHistory: "9-year-old boy presents with right thigh pain and intermittent fevers over 4 weeks. Blood tests show elevated ESR and LDH. Plain films show a permeative lesion of the mid-femoral diaphysis.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 7,
    title: "Giant Cell Tumour of the Distal Radius",
    section: "Expansile lytic lesion",
    modality: "Plain Film",
    clinicalHistory: "32-year-old female with progressive wrist pain over 3 months. No trauma. Examination reveals mild swelling over the distal radius.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 8,
    title: "Enchondroma of the Proximal Phalanx",
    section: "Expansile lytic lesion",
    modality: "Plain Film",
    clinicalHistory: "40-year-old female presents with incidental finding on hand radiograph performed after minor trauma. No significant pain at the lesion site.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [1, 3, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 9,
    title: "Chondrosarcoma of the Proximal Humerus",
    section: "Aggressive bone lesion",
    modality: "MRI",
    clinicalHistory: "58-year-old male with an enlarging painful mass over the right shoulder for 6 months. Plain films demonstrate a large destructive lesion with chondroid matrix calcification in the proximal humerus.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "advanced",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 10,
    title: "Solitary Bone Metastasis — Renal Cell Carcinoma",
    section: "Aggressive bone lesion",
    modality: "CT",
    clinicalHistory: "62-year-old male with known renal cell carcinoma. Presents with new onset right hip pain. CT pelvis performed for staging.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 11,
    title: "Rheumatoid Arthritis — Hands",
    section: "Inflammatory arthropathy",
    modality: "Plain Film",
    clinicalHistory: "48-year-old female with a 5-year history of bilateral hand pain and morning stiffness lasting over 1 hour. RF positive. Referred for baseline radiographic assessment.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 12,
    title: "Ankylosing Spondylitis — Sacroiliac Joints and Spine",
    section: "Inflammatory arthropathy",
    modality: "Plain Film",
    clinicalHistory: "26-year-old male with chronic low back pain and early morning stiffness improving with exercise. HLA-B27 positive. Pain has been present for over 2 years.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 13,
    title: "Gout — First Metatarsophalangeal Joint",
    section: "Crystal arthropathy",
    modality: "Plain Film",
    clinicalHistory: "55-year-old male with recurrent acute episodes of painful swelling of the right great toe over 8 years. Serum urate consistently elevated. Current acute flare.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 14,
    title: "CPPD — Knee (Chondrocalcinosis)",
    section: "Crystal arthropathy",
    modality: "Plain Film",
    clinicalHistory: "72-year-old female presents with acute right knee pain and swelling. No trauma. Aspirate shows positively birefringent rhomboid crystals.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 15,
    title: "Psoriatic Arthritis — Hands and Feet",
    section: "Inflammatory arthropathy",
    modality: "Plain Film",
    clinicalHistory: "38-year-old male with known psoriasis and a 2-year history of asymmetric joint pain and swelling affecting the fingers and toes. Dactylitis of the left ring finger.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 16,
    title: "Paget Disease of the Pelvis",
    section: "Metabolic bone disease",
    modality: "Plain Film",
    clinicalHistory: "70-year-old male with progressive right hip and pelvic pain. Markedly elevated alkaline phosphatase (ALP 1200 IU/L). Normal calcium and phosphate.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 17,
    title: "Primary Hyperparathyroidism",
    section: "Metabolic bone disease",
    modality: "Plain Film",
    clinicalHistory: "52-year-old female with fatigue, bone pain, and renal calculi. Blood tests show elevated calcium (3.1 mmol/L) and elevated PTH. Hand and skull radiographs requested.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 18,
    title: "Osteoporotic Vertebral Compression Fractures",
    section: "Metabolic bone disease",
    modality: "Plain Film",
    clinicalHistory: "78-year-old female with acute thoracolumbar pain after bending to pick up a bag. History of osteoporosis. On no treatment. DEXA T-score -3.4.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 5, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 19,
    title: "Rickets",
    section: "Metabolic bone disease",
    modality: "Plain Film",
    clinicalHistory: "18-month-old child with failure to thrive, bowed legs, and delayed walking. Vitamin D level markedly reduced. Wrist and knee radiographs requested.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 20,
    title: "Acute Osteomyelitis — Paediatric Tibia",
    section: "Osteomyelitis & infection",
    modality: "MRI",
    clinicalHistory: "5-year-old boy with 5-day history of right leg pain and refusal to weight-bear. Temperature 38.8°C. CRP 120 mg/L, WCC 18 x 10^9/L. Plain films show soft tissue swelling only.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 21,
    title: "Brodie Abscess — Proximal Tibia",
    section: "Osteomyelitis & infection",
    modality: "MRI",
    clinicalHistory: "12-year-old boy with 6-week history of right knee pain. Low-grade temperature. CRP mildly elevated. Plain film shows a lucent lesion in the proximal tibial metaphysis with a sclerotic rim.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 22,
    title: "Spinal Tuberculosis (Pott Disease) — Thoracolumbar Spine",
    section: "Osteomyelitis & infection",
    modality: "MRI",
    clinicalHistory: "35-year-old male recently arrived from South Asia with 3-month history of back pain, weight loss, and night sweats. Mantoux test strongly positive.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 23,
    title: "Developmental Dysplasia of the Hip (DDH)",
    section: "Skeletal dysplasia & developmental",
    modality: "Plain Film",
    clinicalHistory: "14-month-old girl with delayed walking and asymmetric skin creases. Breech delivery. Ortolani test equivocal. Pelvic radiograph requested.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 24,
    title: "Achondroplasia",
    section: "Skeletal dysplasia & developmental",
    modality: "Plain Film",
    clinicalHistory: "Newborn with short limbs, macrocephaly, and frontal bossing. Skeletal survey performed.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: false,
    textbookRefs: [1, 3, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 25,
    title: "ACL Tear with Bone Bruise Pattern",
    section: "Joint instability & internal derangement",
    modality: "MRI",
    clinicalHistory: "20-year-old female footballer with acute knee injury during a pivoting manoeuvre. Immediate effusion. Lachman test positive. Clinical suspicion of ACL injury.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 26,
    title: "Meniscal Bucket-Handle Tear",
    section: "Joint instability & internal derangement",
    modality: "MRI",
    clinicalHistory: "30-year-old male presents with locked knee following a twisting injury 2 days ago. Unable to fully extend the knee. Effusion present.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 27,
    title: "Avascular Necrosis of the Femoral Head",
    section: "Osteonecrosis",
    modality: "MRI",
    clinicalHistory: "42-year-old male with bilateral hip pain. History of long-term corticosteroid use for SLE. Plain films show subtle sclerosis of the right femoral head. MRI for further evaluation.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 28,
    title: "Non-Accidental Injury (NAI) — Skeletal Survey",
    section: "Soft tissue & synovial",
    modality: "Plain Film",
    clinicalHistory: "4-month-old infant brought to A&E with alleged fall from sofa. Swollen left arm. Skeletal survey performed as per safeguarding protocol.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 29,
    title: "Lisfranc Fracture-Dislocation",
    section: "Fractures & trauma",
    modality: "CT",
    clinicalHistory: "29-year-old male involved in a road traffic accident. Midfoot pain and swelling. Weight-bearing AP radiograph shows subtle widening between the first and second metatarsal bases. CT for further evaluation.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [2, 3, 4, 5],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 30,
    title: "Jefferson Fracture (C1 Burst Fracture)",
    section: "Fractures & trauma",
    modality: "CT",
    clinicalHistory: "50-year-old male presents after diving into shallow water. Neck pain and restricted cervical movement. Neurologically intact. Open-mouth odontoid view suggests lateral mass offset.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: false,
    textbookRefs: [2, 4, 5, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 31,
    title: "Multiple Myeloma — Skull and Axial Skeleton",
    section: "Multiple lucent bone lesions",
    modality: "Plain Film",
    clinicalHistory: "68-year-old male with back pain, fatigue, and anaemia. Blood tests show elevated total protein with a monoclonal band on serum electrophoresis. Bence Jones protein positive. Skeletal survey requested.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 32,
    title: "Paget Disease — Bone Scan Staging",
    section: "Soft tissue & synovial",
    modality: "Nuclear Medicine",
    clinicalHistory: "72-year-old male with known Paget disease of the right hemipelvis diagnosed on plain film. Bone scan requested to assess polyostotic involvement prior to treatment with bisphosphonates.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 6],
    examPearl: "",
    nuclearMedicine: true,
  },
  {
    caseNumber: 33,
    title: "Bone Metastases — Bone Scan (Prostate Carcinoma)",
    section: "Soft tissue & synovial",
    modality: "Nuclear Medicine",
    clinicalHistory: "74-year-old male with newly diagnosed prostate carcinoma (Gleason 4+4). PSA 85 ng/mL. Bone scan performed for staging to assess for skeletal metastases.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 6, 7],
    examPearl: "",
    nuclearMedicine: true,
  },
  {
    caseNumber: 34,
    title: "Stress Fracture — Bone Scan (Tibial Shaft)",
    section: "Soft tissue & synovial",
    modality: "Nuclear Medicine",
    clinicalHistory: "24-year-old female military recruit with 3-week history of progressive right shin pain exacerbated by marching. Plain films normal. Bone scan performed.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [2, 4, 6],
    examPearl: "",
    nuclearMedicine: true,
  },
  {
    caseNumber: 35,
    title: "Osteoid Osteoma — Proximal Femur",
    section: "Soft tissue & synovial",
    modality: "CT",
    clinicalHistory: "18-year-old male with 6-month history of right hip pain, characteristically worse at night and relieved by NSAIDs. Plain film shows cortical thickening of the proximal femur. CT for nidus localisation.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "intermediate",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 36,
    title: "Rotator Cuff Tear — Full Thickness Supraspinatus",
    section: "Soft tissue & synovial",
    modality: "MRI",
    clinicalHistory: "60-year-old female with chronic right shoulder pain and weakness of abduction. Failed conservative management. Positive empty can test.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "core",
    hasDiscriminator: false,
    textbookRefs: [2, 4, 6],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 37,
    title: "Sacral Insufficiency Fracture — Bone Scan",
    section: "Osteonecrosis",
    modality: "Nuclear Medicine",
    clinicalHistory: "80-year-old female on long-term corticosteroids for polymyalgia rheumatica. Presents with severe low back and buttock pain. Plain films of the pelvis unremarkable. Bone scan performed.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "advanced",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 6, 7],
    examPearl: "",
    nuclearMedicine: true,
  },
  {
    caseNumber: 38,
    title: "Pigmented Villonodular Synovitis (PVNS) — Knee",
    section: "Soft tissue & synovial",
    modality: "MRI",
    clinicalHistory: "34-year-old male with chronic right knee pain and recurrent haemorrhagic effusions over 18 months. No trauma. Aspirate shows blood-stained fluid.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "advanced",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 39,
    title: "Neuropathic (Charcot) Joint — Ankle",
    section: "Soft tissue & synovial",
    modality: "Plain Film",
    clinicalHistory: "58-year-old male with long-standing poorly controlled type 2 diabetes mellitus. Presents with a swollen, warm, deformed right ankle. Surprisingly little pain despite the degree of deformity.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "advanced",
    hasDiscriminator: true,
    textbookRefs: [1, 2, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
  {
    caseNumber: 40,
    title: "Fibrous Dysplasia — Proximal Femur (Shepherd's Crook Deformity)",
    section: "Expansile lytic lesion",
    modality: "Plain Film",
    clinicalHistory: "25-year-old female with progressive right thigh pain and limp over 2 years. No history of trauma. Examination reveals leg length discrepancy. Referred for radiographic evaluation.",
    findings: "",
    interpretation: "",
    diagnosis: "",
    differentials: [] as string[],
    nextSteps: "",
    keyBullets: [] as string[],
    importantNegatives: [] as string[],
    difficulty: "advanced",
    hasDiscriminator: true,
    textbookRefs: [1, 3, 4, 6, 7],
    examPearl: "",
    nuclearMedicine: false,
  },
];
